{% set name = "drf-pydantic" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drf_pydantic-{{ version }}.tar.gz
  sha256: 4ee36ef549a0d0d22e9c52c287572128f66e0d56f7619e3844363d49193af5d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - pydantic >=1.9.0,<2.0.0
    - djangorestframework >=3.13.0,<4.0.0

test:
  imports:
    - drf_pydantic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/georgebv/drf-pydantic
  summary: Use pydantic with the Django REST framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
